
export const ADD_LOCAL_HISTORY_SEARCH_ITEM = "ADD_LOCAL_SEARCH_ITEM"
export const REMOVE_LOCAL_HISTORY_SEARCH_ITEM = "REMOVE_LOCAL_HISTORY_SEARCH_ITEM"
export const CLEAR_LOCAL_HISTORY = "CLEAR_LOCAL_HISTORY"

/* TODO: another time... */
/* export const SAVE_CHARACTER_LIST = "SAVE_CHARACTER_LIST"
export const SAVE_FILM_LIST = "SAVE_FILM_LIST" */